# -*- coding: utf-8 -*-
"""tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKb22Sx9eYe92I-Io44DM6CtsDW95UIY
"""

import math


class Tracker:
    def __init__(self, dist_threshold=100):
        self.objects = {}      # {id: centroid}
        self.next_id = 0
        self.dist_threshold = dist_threshold

    def update(self, boxes):
        tracks = []
        new_objects = {}

        for bbox in boxes:
            cx = float((bbox[0] + bbox[2]) / 2.0)
            cy = float((bbox[1] + bbox[3]) / 2.0)

            best_id = -1
            best_dist = float('inf')

            for obj_id, old_centroid in self.objects.items():
                old_cx, old_cy = old_centroid
                dist = math.hypot(cx - old_cx, cy - old_cy)
                if dist < best_dist:
                    best_dist = dist
                    best_id = obj_id

            if best_id >= 0 and best_dist < self.dist_threshold:
                new_objects[best_id] = (cx, cy)
                tracks.append((best_id, bbox))
            else:
                new_objects[self.next_id] = (cx, cy)
                tracks.append((self.next_id, bbox))
                self.next_id += 1

        self.objects = new_objects
        return tracks